name: Auto Commit and Push

on:
  push:
    branches:
      - master  # Cambia 'master' si tu rama principal tiene otro nombre

jobs:
  auto-commit-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        
    - name: Make changes
      run: |
        # Aquí es donde haces los cambios a tu código. Puedes agregar tus scripts de automatización.
        echo "Making automated changes"
        # Ejemplo: echo "Some new content" >> file.txt
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Automated commit" || echo "No changes to commit"
        
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master  # Cambia 'master' por el nombre de tu rama principal si es diferente
